# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ToursApp' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge',
    'DevSupport'
  ]


# Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'ToursAppTests' do
    inherit! :search_paths
# Pods for testing
  end

end

target 'ToursApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for toursapp-tvOS

  target 'ToursApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
